#!/usr/bin/env node
/**
 * Wiki Index — global INDEX.md for the compiled wiki.
 *
 * Karpathy's llm-wiki pattern relies on index-first retrieval: an agent (or a
 * human in Obsidian) reads a single catalogue of every page with a one-line
 * summary, then drills into the pages it needs. This script builds that
 * catalogue deterministically from the compiled output — no LLM call, no DB
 * access. Safe to run after every compile.
 *
 * Reads:
 *   {out-dir}/entities/*.md   (entity wiki pages with YAML frontmatter)
 *   {out-dir}/topics/*.md     (topic synthesis pages)
 *
 * Writes:
 *   {out-dir}/INDEX.md        (regenerated wholesale — never edit by hand)
 *
 * Usage:
 *   node recipes/wiki-compiler/build-index.mjs [--out-dir <path>]
 */

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(HERE, "..", "..");
const DEFAULT_OUT_DIR = path.join(REPO_ROOT, "compiled-wiki");

// Display order + labels for entity type groups. Unknown types sort last.
const TYPE_ORDER = ["person", "organization", "project", "topic", "tool", "place"];

function parseArgs(argv) {
  const args = { outDir: DEFAULT_OUT_DIR };
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a === "--out-dir") args.outDir = path.resolve(REPO_ROOT, argv[++i]);
    else if (a.startsWith("--out-dir=")) args.outDir = path.resolve(REPO_ROOT, a.slice(10));
    else if (a === "--help" || a === "-h") args.help = true;
  }
  return args;
}

function parseFrontmatter(raw) {
  // Minimal YAML frontmatter reader — flat `key: value` lines only, which is
  // exactly what our generators emit. Returns {} when absent.
  if (!raw.startsWith("---")) return {};
  const end = raw.indexOf("\n---", 3);
  if (end === -1) return {};
  const out = {};
  for (const line of raw.slice(3, end).split("\n")) {
    const m = line.match(/^([A-Za-z0-9_]+):\s*(.*)$/);
    if (!m) continue;
    let v = m[2].trim();
    if (v.startsWith('"') && v.endsWith('"')) {
      try {
        v = JSON.parse(v);
      } catch {
        /* keep raw */
      }
    }
    out[m[1]] = v;
  }
  return out;
}

function firstSummarySentence(raw, maxLen = 160) {
  // First sentence under `## Summary`, else first prose paragraph after the
  // H1. Truncated for one-line index display.
  const body = raw.replace(/^---[\s\S]*?\n---\n/, "");
  let text = null;
  const summary = body.match(/^## Summary\s*\n+([\s\S]*?)(?=\n## |\n*$)/m);
  if (summary) {
    text = summary[1];
  } else {
    const afterH1 = body.match(/^# .*\n+((?:[^#>\n-][^\n]*\n?)+)/m);
    if (afterH1) text = afterH1[1];
  }
  if (!text) return "";
  const flat = text
    .replace(/\[#[0-9a-f-]+(?:,\s*#[0-9a-f-]+)*\]/gi, "") // strip citations
    .replace(/\[\[([^\]|]+)\|([^\]]+)\]\]/g, "$2") // unwrap wikilinks
    .replace(/\[\[([^\]]+)\]\]/g, "$1")
    .replace(/\s+/g, " ")
    .trim();
  const sentence = flat.match(/^.*?[.!?](?=\s|$)/);
  const line = (sentence ? sentence[0] : flat).trim();
  return line.length > maxLen ? line.slice(0, maxLen - 1).trimEnd() + "…" : line;
}

function collectPages(dir, kind) {
  let files = [];
  try {
    files = fs.readdirSync(dir).filter((f) => f.endsWith(".md") && f !== "INDEX.md");
  } catch {
    return [];
  }
  const pages = [];
  for (const f of files) {
    const p = path.join(dir, f);
    let raw;
    try {
      raw = fs.readFileSync(p, "utf8");
    } catch {
      continue;
    }
    const fm = parseFrontmatter(raw);
    pages.push({
      kind,
      slug: f.replace(/\.md$/, ""),
      file: f,
      name: fm.entity_name || fm.title || fm.subject || f.replace(/\.md$/, ""),
      entityType: fm.entity_type || null,
      confidence: fm.confidence || null,
      generatedAt: fm.generated_at || null,
      linkedCount: fm.linked_thought_count != null ? Number(fm.linked_thought_count) : null,
      summary: firstSummarySentence(raw),
    });
  }
  return pages;
}

function renderIndex(entityPages, topicPages) {
  const now = new Date().toISOString();
  const lines = [
    "# Compiled Wiki — Index",
    "",
    `> Regenerated ${now} — ${entityPages.length} entity page(s), ${topicPages.length} topic page(s).`,
    "> This file is generated by build-index.mjs. Do not edit by hand.",
    "",
  ];

  if (topicPages.length > 0) {
    lines.push("## Topics", "");
    for (const p of topicPages.sort((a, b) => a.name.localeCompare(b.name))) {
      const desc = p.summary ? ` — ${p.summary}` : "";
      lines.push(`- [[${p.slug}|${p.name}]]${desc}`);
    }
    lines.push("");
  }

  // Group entities by type, in a stable curated order.
  const byType = new Map();
  for (const p of entityPages) {
    const t = p.entityType || "other";
    if (!byType.has(t)) byType.set(t, []);
    byType.get(t).push(p);
  }
  const types = Array.from(byType.keys()).sort((a, b) => {
    const ia = TYPE_ORDER.indexOf(a);
    const ib = TYPE_ORDER.indexOf(b);
    return (ia === -1 ? 99 : ia) - (ib === -1 ? 99 : ib) || a.localeCompare(b);
  });

  for (const t of types) {
    const group = byType.get(t).sort((a, b) => a.name.localeCompare(b.name));
    const label = t.charAt(0).toUpperCase() + t.slice(1);
    lines.push(`## ${label} (${group.length})`, "");
    for (const p of group) {
      const conf = p.confidence && p.confidence !== "high" ? ` \`${p.confidence}\`` : "";
      const desc = p.summary ? ` — ${p.summary}` : "";
      lines.push(`- [[${p.slug}|${p.name}]]${conf}${desc}`);
    }
    lines.push("");
  }

  return lines.join("\n").trimEnd() + "\n";
}

function main() {
  const args = parseArgs(process.argv.slice(2));
  if (args.help) {
    console.log("Usage: node recipes/wiki-compiler/build-index.mjs [--out-dir <path>]");
    return;
  }
  const entityPages = collectPages(path.join(args.outDir, "entities"), "entity");
  const topicPages = collectPages(path.join(args.outDir, "topics"), "topic");
  if (entityPages.length === 0 && topicPages.length === 0) {
    console.warn(`[wiki-index] nothing to index under ${args.outDir}`);
    return;
  }
  const indexPath = path.join(args.outDir, "INDEX.md");
  fs.writeFileSync(indexPath, renderIndex(entityPages, topicPages), "utf8");
  console.log(
    `[wiki-index] wrote ${indexPath} (${entityPages.length} entities, ${topicPages.length} topics)`,
  );
}

main();
